### ISSUE TITLE
Newer kernel notification even if kernel for current arch unavailable due to build failure.

### ISSUE THREAD

**Issue by satmandu** [pimlie/ubuntu-mainline-kernel.sh#10]
Running on an amd64 system today shows this:

```
./ubuntu-mainline-kernel.sh -c
Finding latest version available on kernel.ubuntu.com: v4.20.2
Finding latest installed version: v4.20.0-042000
A newer kernel version (v4.20.2) is available
```

However as per https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.2/ the amd64 4.20.2 kernel failed to build properly

```
Build for amd64 failed (see BUILD.LOG.amd64):
  linux-headers-4.20.2-042002_4.20.2-042002.201901130931_all.deb
  *_amd64.deb
```
Ideally the script should check to make sure there isn't a "Build for arch failed" line before reporting that kernel as available for the arch the script is being run on.

**Comment by hackel** [comment]
Aha, I was so confused why the script was only installing linux-headers without the image for 4.20.1 and 4.20.2.  Failed build detection would be a most welcome addition.  I added a simple warning if no linux-image-* is present prior to downloading:

```patch
diff --git a/ubuntu-mainline-kernel.sh b/ubuntu-mainline-kernel.sh
index 63c88a8..a010548 100755
--- a/ubuntu-mainline-kernel.sh
+++ b/ubuntu-mainline-kernel.sh
@@ -500,6 +500,14 @@ Optional:
         done
         unset IFS
 
+        if [ $do_install -gt 0 ] && ! containsElement "linux-image" "${FILES[@]}" && [ $assume_yes -eq 0 ]; then
+            logn "It seems there is no image available for version $version, continue? (y/N) "
+            [ $quite -eq 0 ] && read -rsn1 continue
+            log
+
+            [ "$continue" != "y" ] && [ "$continue" != "Y" ] && { exit 0; }
+        fi
+
         debs=()
         log "Will download ${#FILES[@]} files from $ppa_host:"
         for file in "${FILES[@]}"; do
```

**Comment by pimlie** [comment]
Thanks for the comments/suggestions, I have added both a check on the text 'Build succesfull' as the number of files we normally expect to need to download (should be 6 for for checksum, signature, header-all, header-arch, image(-unsigned), modules)

Let me know if you have other suggestions
