### ISSUE TITLE
After script install an error with -c

### ISSUE THREAD

**Issue by montvid** [pimlie/ubuntu-mainline-kernel.sh#12]
```
sudo ubuntu-mainline-kernel.sh -c
Finding latest version available on kernel.ubuntu.com: v4.20.4
Finding latest installed version: none
/usr/local/bin/ubuntu-mainline-kernel.sh: eilutė 401: sorted: blogas masyvo indeksas
A newer kernel version (v4.20.4) is available, latest in current branch is
```

**Comment by pimlie** [comment]
@montvid Thanks for the report, it already says `none` above but can you confirm you didnt have any Ubuntu mainline kernels installed yet? I think the error occurs when its trying to find the latest kernel in your current branch, and it doesnt check if you actually have a 'current' branch

**Comment by montvid** [comment]
Yes, i confirm that i was on default lts, i was concerned about an error in line 401?

**Comment by pimlie** [comment]
Great, thanks for the quick update. Please check the latest version, this just skips comparing the current branch to remote if it doesnt find a current branch

**Comment by montvid** [comment]
just downloaded the repo again and the problem seems not to be fixed:
`Finding latest version available on kernel.ubuntu.com: v4.20.5
Finding latest installed version: none
./ubuntu-mainline-kernel.sh: eilutė 401: sorted: blogas masyvo indeksas
A newer kernel version (v4.20.5) is available, latest in current branch is `

Bad massive index

**Comment by pimlie** [comment]
@montvid Hmm, oops :baby: 

I needed to check for `none` and not just empty string, sorry about that. Should be fix now for real (I double tripple checked) ;)
