### ISSUE TITLE
No issue - just wanted to say thank you

### ISSUE THREAD

**Issue by dreamcat4** [pimlie/ubuntu-mainline-kernel.sh#17]
Hi there,
As someone who needs to download and install the `lowlatency` versions of the kernel, I have been struggling recently with finding a replacement for other tool(s). Which for one or other reason(s) were broken in various ways.

Thank you for taking the time to write and be providing this script, since it works much more as expected, and with little fuss or issues. The command line flags and usage is exceptionally easy to the the end user. Kernel installed! - Thank you so much. Look forwards to re-running this tool again and again. Many times in the future. Kind regards.

**Comment by pimlie** [comment]
Thank you for your kind words!

Its always nice to receive any feedback, but feedback like yours is what we as developers are probably all aiming for. So its very much appreciated and I am happy this script could live up to your expectations  :)
