### ISSUE TITLE
script is ignoring dkms modules (they won't be rebuild)

### ISSUE THREAD

**Issue by Liemaeu** [pimlie/ubuntu-mainline-kernel.sh#18]
e.g. I had to reinstall the nvidia drivers. My wifi drivers (rtl8812au-dkms) and virtualbox do no longer work!

**Comment by gothicVI** [comment]
That is not an issue of the script at all. It's an issue of the programs providing the modules not providing updated modules for newer kernels.
If that happens either update the affected programs or downgrade the kernel version.
