### ISSUE TITLE
Patch to KDE Neon

### ISSUE THREAD

**Issue by tiago4171** [pimlie/ubuntu-mainline-kernel.sh#2]
Hi,
First of all, sorry for my bad english. I Tried to do my best in this text
I'm using KDE Neon, that is based in Ubuntu LTS. I Tried to run this script today and I Get this error:

> "Abort, this script is only intended for Ubuntu and LinuxMint"

In theory it was supposed to work, cause the KDE Neon is based on Ubuntu 16.04. So a quick look at the code, I saw this:

> **OS=$(lsb_release -si 2>&-)
> [[ "$OS" == "Ubuntu" ]] || [[ "$OS" == "LinuxMint" ]] || {**
> 	echo "Abort, this script is only intended for Ubuntu and LinuxMint"
> 	exit 2
> }

so I figured that adding "neon" after Linux mint with the same syntax this work. And yeah I was right, that worked without any alteration on my system, all dependencies were already installed.

So the question is, Why limit this script only to Ubuntu and Linux Mint if there are many other distros based on them?

The attach below is the patched script to work on Neon. If you need some help to test your script in other distros based on Ubuntu, please tell me. I love testing other systems 👍 

[ubuntu-mainline-kernel.txt](https://github.com/pimlie/ubuntu-mainline-kernel.sh/files/1619447/ubuntu-mainline-kernel.txt)

Hope it helps. Thanks a lot!

**Comment by pimlie** [comment]
Hi, thanks. The main reason I have (up to now) only included Ubuntu/LinuxMint was just that I use those and no others :)

Could you maybe check something for me? Do you have a file `/etc/os-release` in KDE Neon? If so, could you post it contents? Maybe I can implement a more generic solution with that file

**Comment by tiago4171** [comment]
Of course I can.
There it is

> NAME="KDE neon"
> VERSION="5.11"
> ID=neon
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="KDE neon User Edition 5.11"
> VERSION_ID="16.04"
> HOME_URL="http://neon.kde.org/"
> SUPPORT_URL="http://neon.kde.org/"
> BUG_REPORT_URL="http://bugs.kde.org/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

**Comment by pimlie** [comment]
Great thanks, I just pushed some changes that checks ID and ID_LIKE for ubuntu if the os-release file exists. Hope this helps!

And your English is great btw :1st_place_medal:
