### ISSUE TITLE
Don't use sudo inside the script

### ISSUE THREAD

**Issue by rockerbacon** [pimlie/ubuntu-mainline-kernel.sh#20]
I was running the script freely believing that as long as I didn't use sudo nothing would be changed, since that's the default behaviour of almost every script and application I've used.

The problem of using sudo inside the script is that if a command was run with sudo before the script most terminals will not prompt for a password again. Eg:
```
sudo find ./ -name something
./ubuntu-mainline-kernel.sh -i 5.3.0
```
No privilege elevation will be done explicitly and the script will still download and install kernel 5.3.0

**Comment by gothicVI** [comment]
That's indeed a concern. My pull request, https://github.com/pimlie/ubuntu-mainline-kernel.sh/pull/21, should fix that.
I'm currently at work and thus can't test it.

**Comment by pimlie** [comment]
Why do you want to run the install command but dont install it? There is already a confirmation step which ask if you want to continue or not.

This script is supposed to help make things easier, having to type root passwords every single time doesnt sound like that. That said, you are free to adjust the sudo command like @gothicVI proposed. That was the idea at least behind extracting the commands to the config section to make sure that you can easily adjust it to your personal preference in situations like this ;)

**Comment by rockerbacon** [comment]
> Why do you want to run the install command but dont install it?
Testing out the script. I was expecting to be able to safely run everything without worrying about actually getting a kernel installed/uninstalled and got very surprised when I saw no errors.

> having to type root passwords every single time
I believe we're not on the exact same page here. I'm not suggesting invalidating cached credentials so a password is required every time, I'm suggesting following the standard which is that the user is always the one responsible for elevating privileges. eg:

```
./ubuntu-mainline-kernel.sh -i 5.3.0
```
Raises error as it was not run as sudo and installing a kernel requires root privileges.

```
sudo ./ubuntu-mainline-kernel.sh -i 5.3.0
```
Works fine.

This is the behavior of every other application and script in Linux and GNU. Running multiple sudo commands will not yield multiple password requests because the credentials get cached:
```
sudo ./ubuntu-mainline-kernel.sh -u <very old kernel>
sudo ./ubuntu-mainline-kernel.sh -i <newer kernel>
```
Will ask for a password a single time and only if no other command was run with sudo recently. This is the same amount of times a password is requested with the current script.

**Comment by pimlie** [comment]
Hmm yeah, I understand your point. And partially agree.

But I really think that a script meant to install kernels could be expected to use sudo because everybody knows you need elevated privileges to install a kernel. I have another personal bash script I use and every g*oddamn time I use that script it says `This script should be run as root` because there I didn't use sudo (and have been to lazy to add it). Isn't that just the whole point of automation? That if you expect something to be needed to include/execute it by default?

So again, if you want that behaviour you should be able to do that by just changing the sudo line to an empty string like `sudo=""`.

If you feel we should add a (warning?) message about this in the readme, feel free to make a pr. Happy to add that :)

**Comment by orithena** [comment]
I just stumbled about this issue... I'd propose running `sudo -k` before the first sudo call as a compromise:

> -k [command]
> When used alone, the -k (kill) option to sudo invalidates the user's cached credentials. The next time sudo is run a password will be required. This option does not require a password and was added to allow a user to revoke sudo permissions from a .logout file. Not all security policies support credential caching.

I'd also recommend not to make it necessary to run the script with full sudo permissions. Using sudo only on those points where it is necessary protects the user's system from a bug deleting the wrong system files and suchlike, just because some command's behaviour in the script changed and the variable holding the path to be deleted only contains `/`.

**Comment by gothicVI** [comment]
@orithena I had that suggested in [https://github.com/pimlie/ubuntu-mainline-kernel.sh/pull/21](https://github.com/pimlie/ubuntu-mainline-kernel.sh/pull/21).
You may look at the conversation there as well.

**Comment by pimlie** [comment]
Im ok with adjusting one of the confirmation messages to include a remark about sudo, which people probably wont read either ;)

Or maybe add a cli option `--re-auth` (naming suggestions welcome) that runs `sudo -k` once when the script will use sudo

**Comment by robinpaulson** [comment]
> using sudo inside the script

it does WHAT?! :-)

Yikes, i'm not happy with that either. I prefer to know/control when I run sudo, not have a script do it for me.

Incidentally, I've been running it as so, not realising it would ask even without the sudo prefix:
$ sudo ubuntu-mainline-kernel.sh -c

Which is the same as my pattern for running apt and ukuu (another kernel update utility, now extinct).

> But I think that a script meant to install kernels could be expected to use sudo because everybody knows you need elevated privileges to install a kernel.

Those softwares I mentioned above are also used to install kernels (and other packages), but I don't think many devs, package maintainers or users would be happy if sudo was embedded in them. In which case, I'm the justification from @pimlie is that useful.

**Comment by robinpaulson** [comment]
Thinking more about it, every single software which modifies the system runs the way we're asking for here: systemctl, mkbootimg, grub-update, dpkg, parted, fdisk, synaptic, snap, add-apt-repository, btrfs, fsck, the ntfs utilities, modprobe, rmmod, iptables, mkfs, even visudo!  .... the list goes on and on; I can't think of any which don't. None of them call sudo or su from **inside** the binary or the interpreted script, they wait for the user to explicitly specify it.

Taking this still further, there is no libsudo, making it difficult and obviously bodgy (though not impossible if you **really** want to do it) to call sudo from a compiled c/c++/go, etc. binary, or from a python/perl script. This is probably for a reason. It's only possible to call sudo directly and easily from bash (and ksh, zsh, dash, etc.) for reasons related to shell today being such a gigantic pile of ad-hoc sucky mess with multiple overlapping, bodgy and pointlessly inconsistent implementations.

The more I think about it, the more terrible an idea this appears to be.

**Comment by robinpaulson** [comment]
Thinking more about it, every single software which modifies the system runs the way we're asking for here: systemctl, mkbootimg, grub-update, dpkg, parted, fdisk, synaptic, snap, add-apt-repository, btrfs, fsck, the ntfs utilities, modprobe, rmmod, iptables, mkfs, even visudo!  .... the list goes on and on; I can't think of any which don't. None of them call sudo or su from **inside** the binary or the interpreted script, they wait for the user to explicitly specify it.

Taking this still further, there is no libsudo, making it difficult and obviously bodgy (though not impossible if you **really** want to do it) to call sudo from a compiled c/c++/go, etc. binary, or from a python/perl script. This is probably for a reason. It's only possible to call sudo directly and easily from bash (and ksh, zsh, dash, etc.) for reasons related to shell today being such a gigantic pile of ad-hoc sucky mess with multiple overlapping, bodgy and pointlessly inconsistent implementations.

The more I think about it, the more terrible an idea this appears to be.

**Comment by robinpaulson** [comment]
Thinking more about it, every single software which modifies the system runs the way we're asking for here: systemctl, mkbootimg, grub-update, dpkg, parted, fdisk, synaptic, snap, add-apt-repository, btrfs, fsck, the ntfs utilities, modprobe, rmmod, iptables, mkfs, even visudo!  .... the list goes on and on; I can't think of any which don't. None of them call sudo or su from **inside** the binary or the interpreted script, they wait for the user to explicitly specify it.

Taking this still further, there is no libsudo, making it difficult and obviously bodgy (though not impossible if you **really** want to do it) to call sudo from a compiled c/c++/go, etc. binary, or from a python/perl script. This is probably for a reason. It's only possible to call sudo directly and easily from bash (and ksh, zsh, dash, etc.) for reasons related to shell today being such a gigantic pile of ad-hoc sucky mess with multiple overlapping, bodgy and pointlessly inconsistent implementations.

The more I think about it, the more terrible an idea this appears to be.

**Comment by robinpaulson** [comment]
All: I'm very sorry for the multiple identical posts, my internet connection here in lockdown is dreadful, gh informed me my posts were not successful because of it.

**Comment by rockerbacon** [comment]
> Thinking more about it, every single software which modifies the system runs the way we're asking for here: systemctl, mkbootimg, grub-update, dpkg, parted, fdisk, synaptic, snap, add-apt-repository, btrfs, fsck, the ntfs utilities, modprobe, rmmod, iptables, mkfs, even visudo! .... the list goes on and on; I can't think of any which don't. None of them call sudo or su from **inside** the binary or the interpreted script, they wait for the user to explicitly specify it.
> 
> Taking this still further, there is no libsudo, making it difficult and obviously bodgy (though not impossible if you **really** want to do it) to call sudo from a compiled c/c++/go, etc. binary, or from a python/perl script. This is probably for a reason. It's only possible to call sudo directly and easily from bash (and ksh, zsh, dash, etc.), for reasons related to shell today being such a gigantic pile of ad-hoc sucky mess.
> 
> The more I think about it, the more terrible an idea this appears to be.

Those were my exact thoughts when I opened the issue. The only program I've seen requiring elevation inside itself was sshuttle (which is not bundled in any OS I know of), but even sshuttle will be careful and require credentials every time it is used.

All GNU and other out-of-the-box programs I've ever came across in the Linux world require the entire program to be run as root when doing tasks which require elevated privileges. By the definitions in Linux there's no such thing as a program being executed by two users at the same time, which is why such thing is not common and not the behaviour users expect.

**Comment by pimlie** [comment]
After thinking about it I agree that expected behaviour should be prevalent. Have just removed sudo in the latest version by default, but you can easily uncomment the old config line if you dont care about all this ;)

**Comment by dreamcat4** [comment]
@pimlie This is not complete,

Upgraded recently and could not understand why this tool reported successful installation... when none of the packages were actually installed.

It seems what has happened is that: This `sudo` fix has now caused (elsewhere) a silent failing at the following line:

https://github.com/pimlie/ubuntu-mainline-kernel.sh/blob/master/ubuntu-mainline-kernel.sh#L725

When the `dpkg` command fails to install anything. Since it is without `sudo` being prefixed automatically anymore. What dpkg should say:

```sh
dpkg: error: requested operation requires superuser privilege
```

But that message is somehow being supressed by your script:

```sh
[id:~] $ ubuntu-mainline-kernel.sh -i v5.7.5
Downloading index from kernel.ubuntu.com
Will download 6 files from kernel.ubuntu.com:
Downloading amd64/linux-headers-5.7.5-050705-lowlatency_5.7.5-050705.202006220832_amd64.deb: 100%   
Downloading amd64/linux-headers-5.7.5-050705_5.7.5-050705.202006220832_all.deb: 100%   
Downloading amd64/linux-image-unsigned-5.7.5-050705-lowlatency_5.7.5-050705.202006220832_amd64.deb: 100%   
Downloading amd64/linux-modules-5.7.5-050705-lowlatency_5.7.5-050705.202006220832_amd64.deb: 100%   
Downloading amd64/CHECKSUMS: 100%   
Downloading amd64/CHECKSUMS.gpg: 100%   
Signature of checksum file has been successfully verified
Checksums of deb files have been successfully verified with sha256sum
Installing 4 packages
Cleaning up work folder
[id:~] $ 
```

Nothing was installed.

**Comment by dreamcat4** [comment]
Well you should be throwing an error message, to say why its failed. And also return a non-zero return code.
