### ISSUE TITLE
Is it possible to switch back to the kernel before running ubuntu-mainline-kernel.sh

### ISSUE THREAD

**Issue by wryVotary** [pimlie/ubuntu-mainline-kernel.sh#23]
Hi,

I am running Pop!_OS 19.10 and ran ubuntu-mainline-kernel.sh to see if the latest kernel handles the OLED screen brightness issue. (Unfortunately, it does not :( )

I am curious about how to switch back to the kernel before running the script? Now I can only see one available kernel, which in the latest one, after `ubuntu-mainline-kernel.sh -l`

Thanks.

**Comment by gothicVI** [comment]
Did you remove the previously installed kernel?
If not then just select it in grub during booting.

**Comment by pimlie** [comment]
Sorry for late reaction, this script will only list kernels that you installed from the mainline ppa. If you didnt remove your default distribution kernel its safe to remove the ppa kernel by running `ubuntu-mainline-kernel.sh -u` after which running `ubuntu-mainline-kernel.sh -l` will just show 0 kernels (as you wont have any kernels from the ppa installed anymore).

You can run `dpkg -l linux-image-*` to make sure you still have any other kernels installed

**Comment by wryVotary** [comment]
Thanks for the reply. But... I type "ls /boot" and see the following:
```
ls /boot
config-5.3.0-7625-generic     initrd.img-5.3.0-7625-generic     System.map-5.4.13-050413-generic
config-5.3.0-7629-generic     initrd.img-5.3.0-7629-generic     vmlinuz
config-5.4.13-050413-generic  initrd.img-5.4.13-050413-generic  vmlinuz-5.3.0-7625-generic
efi                           initrd.img.old                    vmlinuz-5.3.0-7629-generic
initrd.img                    System.map-5.3.0-7625-generic     vmlinuz-5.4.13-050413-generic
initrd.img-5.3.0-24-generic   System.map-5.3.0-7629-generic     vmlinuz.old
```

Therefore, I thought I have 5.3.0-7625 and 5.4.13-050413 at the same time then I used mainline-kernel.sh -u remove the kernel 5.4 which was installed by mainline-kernel. Unfortunately, now I am not able to boot into the system and pop OS is still looking for kernel 5.4 based on the error... I guess I missed changing something before rebooting the system. Is there any way to fix it? 

Thanks!

**Comment by pimlie** [comment]
Normally you'd run `update-grub` to recreate the boot-menu, but I'm not familiar with Pop OS so that might work differently

**Comment by wryVotary** [comment]
thanks for the information

**Comment by ponjadito23** [comment]
Pop_OS uses systemd-boot instead of GRUB. systemd-boot keeps a backup of the previous kernel which you can select by pressing space while booting up, but to change to another kernel you need to create an EFI executable for that kernel and copy it to /boot/efi/EFI/Pop_OS, you also need to copy the initrd.img which you can find in /boot

**Comment by ponjadito23** [comment]
I also want to change my kernel back but couldn't find a way to make an EFI executable
