### ISSUE TITLE
Cleaning operation

### ISSUE THREAD

**Issue by dacorsa** [pimlie/ubuntu-mainline-kernel.sh#24]
Goodmorning,
the cleaning operation (sudo kernel-remover -f) doesn't remove the package:
linux-headers-OLD-VERSION*
when there is already installed the new... is a bug?

Thanks

**Comment by pimlie** [comment]
@dacorsa Are you using the latest version of this script? There was an old issue with this indeed, but that should've been fixed a long time ago. Commit that fixed this is ddedb4bb9e346cf6f726bec2ed6780f4440fccb6
