### ISSUE TITLE
Uninstall of installed kernels is not working

### ISSUE THREAD

**Issue by mammuth** [pimlie/ubuntu-mainline-kernel.sh#30]
Running ` ubuntu-mainline-kernel.sh -u <version>` with a previously installed version doesn't uninstall the kernel as expected.
![kernel-delete](https://user-images.githubusercontent.com/3121306/80417789-a1f83a80-88d6-11ea-9ba3-3642a271c246.png)

Running the script with ` --debug` leads shows the following error:
`/usr/local/bin/ubuntu-mainline-kernel.sh: line 783: DEBIAN_FRONTEND=noninteractive: command not found`

I'm running Ubuntu 20.04, with 5.4.20.

**Comment by Migsi** [comment]
Having this issue too. The part which is failing looks quite strange to me, I'm not sure if this is valid bash syntax at all. Maybe that bit of code got messed up?

Non functioning section:
```
                    if $sudo DEBIAN_FRONTEND=noninteractive dpkg --purge "${pckgs[@]}" 2>$debug_target >&2; then
                        log "Kernel $uninstall_version successfully purged"
                        exit 0
                    fi
```

**Comment by chrassig** [comment]
I have had the same error on Ubuntu 18.04. I was able to get a script that is able to uninstall kernels by adding the env command to the if command that resulted in the error:

`if env $sudo DEBIAN_FRONTEND=noninteractive dpkg --purge "${pckgs[@]}" 2>$debug_target >&2; then`

$sudo is empty in my case by the way, I run the script by executing
`sudo ubuntu-mainline-kernel.sh ...`

After adding env to the script, I have also verified that uninstaling a kernel using the script still works if $sudo is filled.

Thanks to glenn jackman, who suggested to use env on stackoverflow:
https://stackoverflow.com/questions/7128542/how-to-set-an-environment-variable-only-for-the-duration-of-the-script

**Comment by pimlie** [comment]
Thanks for suggesting using `env`, fixed in https://github.com/pimlie/ubuntu-mainline-kernel.sh/commit/ddee1661bebc21d7eb26e879ecf3c0532ce3a5f3

This issue appeared after the sudo changes it seems as $sudo is now empty by default
