### ISSUE TITLE
ubuntu-mainline-kernel.sh doen't uninstall kernels

### ISSUE THREAD

**Issue by luizcorreia** [pimlie/ubuntu-mainline-kernel.sh#35]
I can't uninstall two kernels instaled with the script.
This was the terminal copy from execution
ubuntu-mainline-kernel.sh -u
Which kernel version do you wish to uninstall?
[0]: v5.6.11-050611
[1]: v5.6.11-050611
type the number between []: 0
Are you sure you wish to remove kernel version v5.6.11-050611? (y/N)
The following packages will be removed: 
linux-headers-5.6.11-050611:amd64 linux-headers-5.6.11-050611:all linux-headers-5.6.11-050611-generic:amd64 linux-headers-5.6.11-050611-generic:all linux-headers-5.6.11-050611-lowlatency:amd64 linux-headers-5.6.11-050611-lowlatency:all linux-image-5.6.11-050611-generic:amd64 linux-image-5.6.11-050611-lowlatency:amd64 linux-image-unsigned-5.6.11-050611-generic:amd64 linux-image-unsigned-5.6.11-050611-lowlatency:amd64 linux-modules-5.6.11-050611-generic:amd64 linux-modules-5.6.11-050611-lowlatency:amd64
Are you really sure? Do you still have another kernel installed? (y/N)

It's end and do nothing.

The debug shows
/usr/local/bin/ubuntu-mainline-kernel.sh: linha 783: DEBIAN_FRONTEND=noninteractive: comando não encontrado

**Comment by gothicVI** [comment]
Are you running an actual install or in a VM or docker container?
`DEBIAN_FRONTEND=noninteractive` is an environment variable set by you or your config.
Potentially revert it.
Also, what does "comando não encontrado" mean?

**Comment by luizcorreia** [comment]
@gothicVI I'm running an actual install. I downloaded a new version from script and the kernel was uninstalled, but now I'm using the kernel uninstalled without video, I have installed a new one, but it doesn't change.
"comando não encontrado" mean "command not found"

**Comment by gothicVI** [comment]
@pimlie could this be an issue introduced with https://github.com/pimlie/ubuntu-mainline-kernel.sh/commit/ddee1661bebc21d7eb26e879ecf3c0532ce3a5f3?

**Comment by luizcorreia** [comment]
I can't get the system back using the script the kernelstub ( I use Pop_OS) stop working with the script, I had use a live cd and chroot to revert the kernel to lts version

**Comment by zion2285** [comment]
I got similar issue with my pop os machine

**Comment by gothicVI** [comment]
We had some issues with pop os recently, e.g., here: https://github.com/pimlie/ubuntu-mainline-kernel.sh/issues/23, https://github.com/pimlie/ubuntu-mainline-kernel.sh/issues/30.
Eventually something there might be helpful for you?

**Comment by pimlie** [comment]
Its probably related to #30 indeed, try to use the latest version. Does Pop_Os have an `env` command?

In cases like this it could be beneficial to run the script with `--debug` so more info is logged about whats going on. Not sure if it would rly help in this case though

**Comment by zion2285** [comment]
My all network adapters disappeared plus none of USB ports working too. Playing around with systemd-boot but doesn't look any good . --debug option doesnt work either. Im uninstalling all kernels for now

**Comment by gothicVI** [comment]
> My all network adapters disappeared plus none of USB ports working too.

That surely is NOT related to the script.

**Comment by pimlie** [comment]
Closing this issue as it was most likely related to 30, if an issue persists please open a new issue

@zion2285 Please make sure to read the warnings about using this script and installing mainline kernels here: https://github.com/pimlie/ubuntu-mainline-kernel.sh/#warnings
