### ISSUE TITLE
Failed install, due to change in directory structure on kernel.ubuntu.com

### ISSUE THREAD

**Issue by robinpaulson** [pimlie/ubuntu-mainline-kernel.sh#40]
the files are now stored in separate sub-directories, as of 5.7.2. one sub-directory for each architecture

e.g. 
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.2/amd64/

the latest install is failing with an "Expected to need to download 6 files but found 2, continue? (y/N)" error

**Comment by MohakChugh** [comment]
![Screenshot from 2020-06-18 00-12-22](https://user-images.githubusercontent.com/33135218/84936790-69b3f200-b0f8-11ea-9b8d-aba1637ac0a1.png)
 Im facing the exact same issue! Any updates?

**Comment by pimlie** [comment]
Thanks for the report, should be fixed with latest version

**Comment by hswong3i** [comment]
@pimlie confirm get fixed for 5.7.3 ;-)
