### ISSUE TITLE
Change in the folder structure

### ISSUE THREAD

**Issue by risafov** [pimlie/ubuntu-mainline-kernel.sh#42]
After kernel 5.7.2 there is new folder structure. So this script always shows build failed.

**Comment by gothicVI** [comment]
Which version of the script are you running?
Does it include https://github.com/pimlie/ubuntu-mainline-kernel.sh/commit/cfc7a3a5df4be6eeb7b011a1dd6b34dc80c1e7d6 and https://github.com/pimlie/ubuntu-mainline-kernel.sh/commit/14580ea56ae0c592c6b505e41c02270c154c72b1?

**Comment by risafov** [comment]
Sorry, after update all works fine.
