### ISSUE TITLE
[Feature request] alternate downloader

### ISSUE THREAD

**Issue by mritunjaymusale** [pimlie/ubuntu-mainline-kernel.sh#45]
Is it possible to change the downloader from wget to aria2c since it does support checksums and parallel downloads natively?

**Comment by pimlie** [comment]
Thanks for the request.

For the moment Im not interesting in supporting other downloaders. It would only be more hassle to maintain and we cant replace wget totally because some distri's doesnt have aria2 installed by default and I dont want to add it as a dependency
