### ISSUE TITLE
[FEATURE] Self-update option

### ISSUE THREAD

**Issue by akira28** [pimlie/ubuntu-mainline-kernel.sh#46]
It would be cool to have a --self-update option to easily update the script

**Comment by gothicVI** [comment]
You could also use an alias together with a function that allows for argument passing like (untested):
```bash
alias ubuntu-mainline-kernel.sh='function _umk(){ cd /path/to/repo/folder && git pull && ./ubuntu-mainline-kernel.sh "$@"; }; _umk'
```

**Comment by pimlie** [comment]
Added an `--update` option
