### ISSUE TITLE
User feedback seems sparse

### ISSUE THREAD

**Issue by rogersa2k** [pimlie/ubuntu-mainline-kernel.sh#48]
When I first discovered this script, only 2 days ago, I mistakenly forgot to run it via sudo. The script acted like it installed the newest kernel but it was only after I rebooted that I realized what I had done. Some sort of check before exiting the script would be very helpful.

Thanks!

**Comment by robinpaulson** [comment]
this might be useful:
https://stackoverflow.com/questions/18215973/how-to-check-if-running-as-root-in-a-bash-script

with this:

https://stackoverflow.com/a/18216143

**Comment by pimlie** [comment]
This should've been addressed with the fix for #55
