### ISSUE TITLE
Kernel not correctly uninstalled?

### ISSUE THREAD

**Issue by johan171** [pimlie/ubuntu-mainline-kernel.sh#51]
with `sudo ubuntu-mainline-kernel.sh -i` I installed the latest linux kernel (5.5.7). It did not work for me, so I booted using another version (5.5.0). Then removed version 5.5.7 with `sudo ubuntu-mainline-kernel.sh -u`. However, now when I boot, I still get linux kernel 5.5.7, which should be removed. Any ideas how this is possible?

**Comment by pimlie** [comment]
@johan171 If this happens the best is to just run `dpkg -l linux-*` and see what packages are installed and remove those manually. Not sure how this could have happened in the first place, maybe a dkms build failed?
