### ISSUE TITLE
Abort, the amd64 build has not succeeded

### ISSUE THREAD

**Issue by gasdia73** [pimlie/ubuntu-mainline-kernel.sh#53]
I'm on kernel Linux 5.7.0-050700-generic, and I would like to update it, but when I issue the command

sudo ubuntu-mainline-kernel.sh -i

This is the response:
Finding latest version available on kernel.ubuntu.com
Latest version is: v5.7.9, continue? (y/N) 
Abort, the amd64 build has not succeeded

**Comment by gothicVI** [comment]
Are you running the latest version of the script?

**Comment by gasdia73** [comment]
It wasn't.
Now it works as expected, thank you

**Comment by robinpaulson** [comment]
Hi, I'm using the latest version of the script (git pull) and am getting this error too. When I look at the website, all the .deb files are there. I'm not sure what to do.

**Comment by robinpaulson** [comment]
i deleted the script and redownloaded, now it's working. <shrug>
