### ISSUE TITLE
Script doesnt install kernel 4.16.4+ correctly

### ISSUE THREAD

**Issue by pimlie** [pimlie/ubuntu-mainline-kernel.sh#6]
Either something went wrong with the kernel build or the build process has changed for the ubuntu mainline kernels. The issue seems that the linux-image files for amd64 are unsigned and are therefore not picked up by the script. Also a new file `linux-modules` seems to be listed.

Will need to find more info about this to see whether we need to adjust the script or this was a one-time thing.

Possible refs:
- https://askubuntu.com/questions/1027414/build-failed-mainline
- https://askubuntu.com/questions/1028629/kernel-ubuntu-com-kernel-ppa-mainline-v4-16

**Comment by cbertram68** [comment]
Same issue with 4.16.5, I noticed two different kernel modules are unsigned.  UKUU says that in both cases the problem is that Linux-Image is unsigned, this is not the case with 4.16.3.  This is causing my machine to have a kernel panic on boot with either 4.16.4 - 5.

Let me know if you need any screen shots or log files.

**Comment by pimlie** [comment]
Thanks, but I dont think I will need them. I think we will have to wait until the kernel builds are either fixed by Ubuntu or they post an explanation somewhere what changed and why. But I guess they area just a bit busy with Bionic Beaver atm.

Btw, the second link mentions the unsigned part refers to EFI/UEFI keys, but I have no idea why the kernel would crash because of that (or why they did sign i386 but not amd64).

**Comment by pimlie** [comment]
I updated the script to search for the new package names, but the install still fails with: `postinst: linux-update-symlinks: not found` and the uninstall fails with `prerm: linux-check-removal: not found`

**Comment by cbertram68** [comment]
Just FYI, on install, the kernel image fails on dependencies not me, at least that is what happens to me.

**Comment by pimlie** [comment]
I managed to install (and boot) kernel `4.16.7` by installing the following two packages:
- [`linux-base_4.5ubuntu1_all.deb`](https://launchpad.net/ubuntu/xenial/amd64/linux-base/4.5ubuntu1~16.04.1) from the Xenial Proposed repository
- [`libssl1.1_1.1.0h-2+ubuntu16.04.1+deb.sury.org+2_amd64.deb`](https://launchpad.net/~ondrej/+archive/ubuntu/apache2/+build/14506365) from Ondrej Sury's Apache2 ppa

That means I consider this issue fix / closed now :)
