### ISSUE TITLE
False Positive when remote kernel list could not be retrieved

### ISSUE THREAD

**Issue by rogersa2k** [pimlie/ubuntu-mainline-kernel.sh#61]
My wireless dropped just before I went to check for kernel updates and the following happened:

`Finding latest version available on kernel.ubuntu.com:`
`Finding latest installed version: v5.8.14`
`A newer kernel version () was found but the build was not successful`

To verify:
I enabled wireless, checked for updates, and it worked as expected.
I disabled wireless, checked for updates again, and again it did that (see above).

Thanks!

**Comment by pimlie** [comment]
Can confirm, have seen this too but pretty low prio to fix
