### ISSUE TITLE
Script doesn't distinguish between standard and low-latency kernels that are installed

### ISSUE THREAD

**Issue by wdormann** [pimlie/ubuntu-mainline-kernel.sh#63]
Imagine that you have kernel <foo> and then later you decide to install the low-latency variant of that same kernel.  While this script has the ability to remove kernels installed by the script, it won't help in this case.  For example, from a test machine:

$ ubuntu-mainline-kernel.sh -l
v5.8.3-050803
v5.8.3-050803  

Ideally, the low-latency variant should be included in the name.

**Comment by pimlie** [comment]
Closing this as there are no low latency builds included in the Mainline repo anymore, see https://askubuntu.com/questions/1397410/where-are-latest-mainline-low-latency-kernel-packages
