### ISSUE TITLE
Handle kernel build failures

### ISSUE THREAD

**Issue by rogersa2k** [pimlie/ubuntu-mainline-kernel.sh#64]
Here is what I am seeing this morning:

`Finding latest version available on kernel.ubuntu.com
Latest version is: v5.9.5
Abort, the amd64 build has not succeeded`

I still get the desktop alert that a newer kernel is available. Maybe this could be handled better?

**Comment by pimlie** [comment]
Not sure what you mean?

If there is a newer kernel version then it should still be reported, regardless if there was a build error over at Ubuntu. They often fix these build errors within a couple of days/weeks

**Comment by rogersa2k** [comment]
Well, today's build seems to have failed again. I guess what I mean is that maybe the desktop notification could indicate the failure.

`Finding latest version available on kernel.ubuntu.com
Latest version is: v5.9.7
Abort, the amd64 build has not succeeded`

**Comment by brannow** [comment]
since v5.7.2, amd64/self-tests failed in almost all builds
see: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.2/ ... https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.12/

last "all tests success" kernel: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.1/

from what I read online, there is nothing "wrong" with the kernel itself and installations on amd systems seems fine.

 
maybe a force flag that ignores failed tests?
it's extremely dangerous but atm this script is for AMD based systems not useable

**Comment by jonseppanen** [comment]
A force flag would be good for many reasons. Is there anyone working on that?

**Comment by pimlie** [comment]
@brannow We dont check _amd64/self-tests_ atm, we only check _amd64/build_? Maybe something changes in the mean time but if I run `sudo ./ubuntu-mainline-kernel.sh -i 5.7.2` _now_ it will just install that kernel?

@jonseppanen Im not sure about that, eg the build for 5.9.13 is just really broken atm. If we are matching the wrong error messages for the build check we should just fix that I suppose

**Comment by gothicVI** [comment]
@pimlie as far as I can see, the error messages rightfully correspond to failed builds only - thus no changes should be needed.
This though seems to come up more often recently as builds seem to fail more often for whatever reasons.

**Comment by hundehausen** [comment]
I have the same issue, how can you still install the newest kernel?

**Comment by gothicVI** [comment]
@hundehausen install the latest that has built fine...

**Comment by brannow** [comment]
@pimlie tested with the latest script version, install kernel version 5.10.1 ... works without any problems,

for me everything is working.
