### ISSUE TITLE
Tab completion when uninstalling kernels

### ISSUE THREAD

**Issue by robinpaulson** [pimlie/ubuntu-mainline-kernel.sh#65]
When I type
$ sudo umk -u [Tab}

It would be nice to get a list of kernels installed by this script, so I can select whichever I wish to uninstall by pressing [Tab] again.

oh, yeah: umk is my shortcut for ubuntu-mainline-kernel.sh

**Comment by pimlie** [comment]
Yeah, would be nice. But afaik we would then need to add another file to `/etc/bash_completion` which might get too complex. I prefer not to have an install script and I also dont think its a good idea to have umk (:smile:) write a bash completion script itself as that good be treated as unwanted behaviour by users

So I think we should hold out on this for now until more people request this

**Comment by robinpaulson** [comment]
I agree it does get a bit more complicated, yes, and it could well be seen as unwanted behaviour. Some responses, though:
* I would suggest putting the file in ~/.local/etc/bash_completion.d/ (I think that's the correct location)
* Perhaps create an option, activated by something like umk -tc, which only writes the file if the user specifically invokes it

**Comment by robinpaulson** [comment]
I realised that if I use the -u option, the script will present a list of kernels and ask which I wish to install. Given that, tab-completion is mostly unnecessary. Closing, apologies for not exploring further earlier.
