### ISSUE TITLE
linux-tools?

### ISSUE THREAD

**Issue by johalun** [pimlie/ubuntu-mainline-kernel.sh#66]
Can this script also install linux-tools? If not, we're can I find that package for the kernel version I installed?

**Comment by gothicVI** [comment]
This is for the kernel packages only.
What exactly are you looking for?

**Comment by johalun** [comment]
linux-tools contain among other the `perf` tool which is built with the kernel. After further investigation it turns out it is not built for the mainline packages. However, Ubuntu's hwe-edge has the kernel version I need to I went with that instead (which has linux-tools packages as well).

Otherwise, one could build it from the source I guess.
