### ISSUE TITLE
Abort, the amd64 build has not succeeded

### ISSUE THREAD

**Issue by damousys** [pimlie/ubuntu-mainline-kernel.sh#67]
When trying to install 
5.9.8 --> 5.9.12 i am getting an error
Abort, the amd64 build has not succeeded
Is there a way to fix that ?

**Comment by gothicVI** [comment]
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.12/ states that the and64 builds succeeded. What platform are you running on?

**Comment by damousys** [comment]
Don't know what I did wrong the first time this morning, but I dit a new try and now it's working fine
