### ISSUE TITLE
[Feature?] Revert back to Ubuntu default distro kernel (or Hardware Enablement Stack)

### ISSUE THREAD

**Issue by mohsh86** [pimlie/ubuntu-mainline-kernel.sh#68]
Is there a way to revert back to default kernel (ubuntu distro kernel) or HWES ?

**Comment by gothicVI** [comment]
Boot it?!
Or did you uninstall it? If so reinstall it and boot it then.

**Comment by pimlie** [comment]
Easiest is to just uninstall all mainline kernels (run with `-u`)

**Comment by mohsh86** [comment]
> Easiest is to just uninstall all mainline kernels (run with `-u`)

would automatically trigger grub and default to previous kernel? want to make sure before i brick a machine half the globe away from me lol

**Comment by pimlie** [comment]
This script just runs `dpkg --purge` with the package names found for the chosen kernel version. If you prefer you can also just uninstall yourself manually. Run `dpkg -l linux-*`, find the 4 packages for the kernel you want to remove and then run `apt purge $pcks` or `dpkg --purge $pcks`.

But note that you get zero guarantees from me as all depends on your understanding of how (kernel) packages works. Ie always best to first try locally so you understand the procedure and what can go wrong before trying it on a remote machine

**Comment by robinpaulson** [comment]
> would automatically trigger grub and default to previous kernel?

there is a script in "post-rm" (or similar) of the kernel .deb files which will trigger grub rebuild. grub will always default to the most recent kernel installed (unless you have a *very* unusual setup), so as long as there is another kernel installed, grub will find it and boot from it next time around

**Comment by mohsh86** [comment]
i have uses -u parameter to uninstall, then used dpkg-reconfigure for ohter version just in case.
