### ISSUE TITLE
it stop pulling linux-image  from ppa

### ISSUE THREAD

**Issue by unixbhaskar** [pimlie/ubuntu-mainline-kernel.sh#7]
From 4.16.4 onwards it stops pulling the linux-image deb package. Because the package file add an "unsigned" word with the name. 

It used to pull 5 files, but after 4.16.4 it's pulling 4 files and missing the linux-image-unsinged file.

Can you please look into it and fix it.

**Comment by pimlie** [comment]
This was fixed recently in #6 

Make sure to also install the required additional dependencies if you are running a distro based on Ubuntu version < 18.04 :)

**Comment by unixbhaskar** [comment]
I do run 18.04 ..then the solution to #6 will work? Not sure.
