### ISSUE TITLE
kernel install failed since v5.10.37, v5.11.21

### ISSUE THREAD

**Issue by eubnara** [pimlie/ubuntu-mainline-kernel.sh#71]
I don't know who is culprit.
Maybe some package are named wrongly?

regex doesn't match
https://github.com/pimlie/ubuntu-mainline-kernel.sh/blob/master/ubuntu-mainline-kernel.sh#L644

![image](https://user-images.githubusercontent.com/12639125/122856676-26ffa800-d352-11eb-8f6e-956c822b4c74.png)

![image](https://user-images.githubusercontent.com/12639125/122856654-1cdda980-d352-11eb-9d8c-73a1de023cf7.png)

**Comment by gothicVI** [comment]
They now seem to incorporate the minimum version coming with the correct library. See also the discussion here: https://github.com/pimlie/ubuntu-mainline-kernel.sh/issues/70.
