### ISSUE TITLE
gpg is required

### ISSUE THREAD

**Issue by jabla** [pimlie/ubuntu-mainline-kernel.sh#73]
If gpg is not installed, the script aborts with the following "unclear" error message:

`Abort, signature of checksum file is NOT OK`

Therefore the gpg dependency should be listed in the installation instructions.

**Comment by gothicVI** [comment]
What Ubuntu (based) system comes without gpg?

**Comment by jabla** [comment]
We have installed ubuntu 18.04 with a netboot mini.iso.

**Comment by pimlie** [comment]
I'd assume that setting `check_signature=0` would've worked, but have added an automated check if gpg is executable.
