### ISSUE TITLE
Support Secure Boot

### ISSUE THREAD

**Issue by t2d** [pimlie/ubuntu-mainline-kernel.sh#75]
Secure Boot is enabled by default in Ubuntu. I think it would be great, if you would support a flag to sign the kernel with an already established key. Thereby, one would only need to enroll the key once manually, but the signing could be done automatically with every update.
Right now, I'm using [this doc](https://gloveboxes.github.io/Ubuntu-for-Azure-Developers/docs/signing-kernel-for-secure-boot.html) to sign the images pulled by this project.

PS: Thank you for the effort you put in this software <3

**Comment by MatejKovacic** [comment]
Any progress on this?

**Comment by gothicVI** [comment]
> Any progress on this?

Noone wrote a pull request, so no.

**Comment by pimlie** [comment]
Added support to self sign kernels, but the script will assume you have already enrolled your own MOK. I also do not plan to add support for creating/enrolling MOK's as its outside the scope of the script
