### ISSUE TITLE
not working with the latest kernel v5.16 

### ISSUE THREAD

**Issue by DaddyMadu** [pimlie/ubuntu-mainline-kernel.sh#77]
for normal kernel 
ubuntu-mainline-kernel.sh -i
Finding latest version available on kernel.ubuntu.com
Latest version is: v5.16.0, continue? (y/N)
Expected to need to download 6 files but found 10, continue? (y/N)
Will download 10 files from kernel.ubuntu.com:
Downloading amd64/linux-headers-5.16.0-051600-generic_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600-generic_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600_5.16.0-051600.202201091830_all.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600_5.16.0-051600.202201092355_all.deb: 100%
Downloading amd64/linux-image-unsigned-5.16.0-051600-generic_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-image-unsigned-5.16.0-051600-generic_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/linux-modules-5.16.0-051600-generic_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-modules-5.16.0-051600-generic_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/CHECKSUMS: 100%
Downloading amd64/CHECKSUMS.gpg: 100%
Signature of checksum file has been successfully verified
Abort, sha256sum returned an error 7

for lowlatency

ubuntu-mainline-kernel.sh --low-latency -i
Finding latest version available on kernel.ubuntu.com
Latest version is: v5.16.0, continue? (y/N)
Expected to need to download 6 files but found 10, continue? (y/N)
Will download 10 files from kernel.ubuntu.com:
Downloading amd64/linux-headers-5.16.0-051600-lowlatency_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600-lowlatency_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600_5.16.0-051600.202201091830_all.deb: 100%
Downloading amd64/linux-headers-5.16.0-051600_5.16.0-051600.202201092355_all.deb: 100%
Downloading amd64/linux-image-unsigned-5.16.0-051600-lowlatency_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-image-unsigned-5.16.0-051600-lowlatency_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/linux-modules-5.16.0-051600-lowlatency_5.16.0-051600.202201091830_amd64.deb: 100%
Downloading amd64/linux-modules-5.16.0-051600-lowlatency_5.16.0-051600.202201092355_amd64.deb: 100%
Downloading amd64/CHECKSUMS: 100%
Downloading amd64/CHECKSUMS.gpg: 100%
Signature of checksum file has been successfully verified
Abort, sha256sum returned an error 7

**Comment by pimlie** [comment]
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/CHECKSUMS is missing checksums for the packages. Not much we can do until that file contains all checksums again

**Comment by DaddyMadu** [comment]
oh. thank you for your speedy answer, you were inactive for a while but i thought to give it a shot anyway!
hope you r doing well!
