### ISSUE TITLE
Abort, the amd64 build has not succeeded

### ISSUE THREAD

**Issue by yxles-dev** [pimlie/ubuntu-mainline-kernel.sh#80]
> $ sudo ubuntu-mainline-kernel.sh -i
> Finding latest version available on kernel.ubuntu.com
> Latest version is: v5.18.5, continue? (y/N)
> Abort, the ad64 build has not succeeded

Help, I read some past issue related to this and said that this was fix on the latest release but this still happens to me even with the latest release

**Comment by gothicVI** [comment]
What do you need help with?
Looking at https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.18.5/ it's clear that the build failed.
Nothing this script can do about that though.
