### ISSUE TITLE
ubuntu-main-line-kernel-sh Abort, the amd64 build has not succeeded

### ISSUE THREAD

**Issue by FrankIJskes** [pimlie/ubuntu-mainline-kernel.sh#83]
The latest kernel version I can install is 6.0.9 with the shell script.
All other builds generate the same error:
Abort, the amd64 build has not succeeded
Starting at v6.0.10 and ending at v6.1.1, all these kernel versions generate the same error.

Used command: /root/ubuntu-mainline-kernel.sh -i v6.1.1

**Comment by pimlie** [comment]
See https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1.1/, the builds really failed so we have to wait until the Ubuntu kernel team fixes them
