### ISSUE TITLE
add .gitattributes

### ISSUE THREAD

**Issue by andkae** [pimlie/ubuntu-mainline-kernel.sh#84]
Hi Pim,

if i check out the repo under Windows and like to use the script in Linux i receive error through the wrong EOL coding. In default Windows checkout with EOL=LFCR, under Linux EOL=LF. Therefore the question to add the file
_.gitattributes._ to your repo with following content

```bash
*.sh text eol=lf
```

This forces to always checkout out *.sh files with LF only end of line. What do you think?

If you like i can prepare an PR?

BR,
Andreas

**Comment by pimlie** [comment]
Yes! Have added it, let me know if its still not ok :)
