### ISSUE TITLE
Lowlatency doesn't pull linux-headers package

### ISSUE THREAD

**Issue by stereoplegic** [pimlie/ubuntu-mainline-kernel.sh#9]
When attempting to run with -ll switch, only linux-headers-[VERSION]-lowlatency is installed (with errors, as it depends on linux-headers-[VERSION]). Generic kernel of same version installs fine, as it installs both linux-headers-[VERSION] and linux-headers-[VERSION]-generic. Only way to install RT mainline with this script is to first install generic mainline.

**Comment by pimlie** [comment]
Thanks for reporting, should be fixed by the latest version!
